export const Cinformation = [
    {value : 'CARBON (c)'},
    {value : 'MANGANESE (Mn)'},
    {value : 'SILICON (Si)'},
    {value : 'SULFUR (S)'},
    {value : 'PHOSPHORUS (P)'},
    {value : 'CHROMIUM (Cr)'},
    {value : 'MOLYBDENUM (Mo)'},
    {value : 'NICKEL (Ni)'},
    {value : 'TITANIUM (Ti)'},
    {value : 'COPPER (Cu)'},
    {value : 'BORON (B)'},
    {value : 'HYDROGEN (H)'},
    {value : 'OXYGEN (O)'},
    {value : 'ZINC (Zn)'},
    {value : 'IRON (Fe)'},
    {value : 'Min'},
    {value : 'ALUMINUM (Al)'},
    {value : 'COBOLT (Co)'},
    {value : 'NITROGEN (N)'},
    {value : 'VANADIUM (V)'},
    {value : 'NIOBIUM (Nb)'},
    {value : 'TANTALUM (Ta)'},
    {value : 'Nb + Ta'},
    {value : 'CORBON EQUIVALENT (CE)'},
    {value : 'TIN (Sn)'},
    {value : 'PREN'},
    {value : 'PREW'},
    {value : 'TUNGSTEN (W)'},
    {value : 'LEAD (Pb)'},
    {value : 'MAGNESIUM (Mg)'},
    ]